[package]
name = "dokan"
version.workspace = true
authors.workspace = true
description = "Rust-friendly wrapper for Dokan (user mode file system library for Windows)"
homepage.workspace = true
repository.workspace = true
documentation = "https://dokan-dev.github.io/dokan-rust-doc/html/dokan/"
keywords = ["dokan", "bindings", "driver", "filesystem"]
categories = ["external-ffi-bindings"]
readme = "README.crates-io.md"
exclude = ["README.md"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[badges]
appveyor = { repository = "Liryna/dokan-rust" }

[features]
default = []
windows-interop = ["dep:windows"]

[dependencies]
bitflags.workspace = true
dokan-sys.workspace = true
widestring.workspace = true
windows = { workspace = true, features = ["Win32_Foundation"], optional = true }

[dev-dependencies]
clap.workspace = true
ctrlc.workspace = true
parking_lot.workspace = true
regex.workspace = true
winapi = { workspace = true, features = ["std", "errhandlingapi", "handleapi", "heapapi", "ioapiset", "minwinbase", "minwindef", "ntdef", "ntstatus", "processenv", "processthreadsapi", "sddl", "securitybaseapi", "synchapi", "winbase", "winerror", "winnt"] }

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[lints]
workspace = true
